### ISSUE TITLE
Logging port forwarding rich rules

### ISSUE THREAD

**Issue by svarshavchik** [firewalld/firewalld#1263]
### What would you like to be added

An option to enable logging for forward connections. <forward-port> does not appear to support a logging option.

### Why is this needed

It would be useful to log forwarded connections.

[A brief discussion was here](https://lists.fedoraproject.org/archives/list/firewalld-users@lists.fedorahosted.org/thread/J2CNTO7Q3CXTFZEBIJRVFHMM7IYLEQM3/)

**Comment by OleHolmNielsen** [comment]
Thanks a lot! We also need to log forwarded connections through our masquerading firewall, and I'd like to use the new loggin feature:
Question: How do we enable logging of forwarded connections?  I couldn't locate any documentation in the firewalld.conf manual page, but maybe it's due to my limited experience with firewalld?
Thanks for providing any example of this!
Ole

**Comment by erig0** [comment]
You need to use a rich rule to do logging + forward-port.

e.g. CLI

```
 #firewall-cmd --add-rich-rule='rule family=ipv4 forward-port port=33 protocol=tcp to-port=33 to-addr=10.10.10.10 log prefix="forward-port: " level="info" limit value="1/m"'
```
