### ISSUE TITLE
Priorities for zone sub-chain calls

### ISSUE THREAD

**Issue by canvon** [firewalld/firewalld#149]
In a zone's iptables chain, e.g., IN_home, there are calls to sub-chains IN_home_log, IN_home_deny, IN_home_allow. If each one had a priority, direct rules could be specified with a later priority, to be inserted after those sub-chain calls.

My use case is this: I've added rich language rules to the home zone to allow service ssh only for certain source-destination address combinations, and now wanted to log-reject (and if limit is exceeded, drop,) further ssh connection attempts. (They should be logged separately from the FINAL_REJECT log entries as I won't regularly take a look at each of them.)

Currently, this does not seem possible with rich-language rules, as they get reordered into all-log-iptables-rules, all-deny-iptables-rules, all-allow-iptables-rules; thus, the "final" ssh reject/drop would happen in the generated firewall _before_ the allow rules, rendering them useless. (?)

Then I tried to add those final ssh reject/drop rules as direct rules, but I couldn't get them to be inserted _after_ the IN_home_allow chain (nor at the end of that chain). Would they have priorities like direct rules, it should have been possible.

I guess I can just use direct rules for _all_ the ssh rules, have all of them at the top of the IN_home chain, as a work-around for now, though. But then I'd not be using rich language rules anymore; so couldn't base such rules on a pre-defined service anymore.

**Comment by erig0** [comment]
If I understand it correctly, you're suggesting we add a "priority" field to rich rules to guarantee their order of execution. This is a good idea, IMO.

**Comment by Sxderp** [comment]
> If I understand it correctly, you're suggesting we add a "priority" field to rich rules to guarantee their order of execution. This is a good idea, IMO.

While that is a good idea, I don't think it will resolve the issue in this ticket. Namely, 'deny' rules are always executed before 'allow' rules, with no way to override such.

For this use case they want to:
- Allow SSH from/to specific source/destinations
- Deny SSH from elsewhere with a unique log message

Without the unique log message this is fairly easy to do. Add allow rules for the sources/destinations and then let the packets fall through the the TARGET (being REJECT or somesuch). This doesn't work when the target is ACCEPT or if you want to additionally or separately log the specific packets (as in this case).

To work around this we have the following options. Use a separate zone and potentially duplicate a lot of rules. Add specific deny rules for everything that is not allowed which is a lot of work and potentially complex when dealing with source AND destination matches. Or add a generic deny SSH rule with associated logging which is evaluated AFTER the the 'IN_zone_allow' chain and BEFORE the generic target / log messages. Furthermore, the log has to occur AFTER the 'IN_zone_allow' chain otherwise you'll log the acceptable packets as rejected.

Which brings up a point about logging that I feel is inherently broken in firewalld. If I associate a rule with a log I expect a packet to only be logged if that accept /  deny / reject / mark rule is actually performed! Not for every matching rule. And there should also be a way to create un-associated log rules (rich rules without action) for the times I want a log divorced from actions taken. I could go on and I should probably make an issue on it, but for the purpose of THIS issue, the concept is still relevant. Logging facilities are extremely limited using firewalld interfaces.

I feel the solution to this issue is basically the last line of #300 
> Even better if I could add multiple target rich rules in a zone (using priority).

So yes, add priority, but add priority for rich rules and add a 'target' location. Perhaps better terminology might be required. But the point is a rich-rule that occurs at the end of the chain. The extended solution is to also fix logging so that only actions that are actually performed are logged!

**Comment by erig0** [comment]
> While that is a good idea, I don't think it will resolve the issue in this ticket. Namely, 'deny' rules are always executed before 'allow' rules, with no way to override such.

I'm suggesting that the priority sort the rich rules into a *new* chain dedicated to rich rules. They would not go into the _deny or _allow chains based on the rule verdict. I believe with this you'd be able do everything you're requesting.

The nftables rules would look like this:
```
 chain filter_IN_public {
         jump filter_IN_public_rich_rule_pre   # priority <  0
         jump filter_IN_public_log             # priority == 0
         jump filter_IN_public_deny            # priority == 0
         jump filter_IN_public_allow           # priority == 0
         jump filter_IN_public_rich_rule_post  # priority >  0
         meta l4proto { icmp, ipv6-icmp } accept
 }
```
priority < 0 rich rules go into filter_IN_public_rich_pre.
priority == 0 rich rules behave as they do today and go into the _log, _deny, _allow chains.
priority > 0 rich rules go into filter_IN_public_rich_post.

Where lower values of "priority" have higher precedence. This matches the current "priority" behavior of direct rules.

This gives the user flexibility to add rich rules before and after the other firewalld primitives (e.g. services, ports, etc.). It also allows user ordering of rich rules.

**Comment by Sxderp** [comment]
Thank you for the clarification. Your suggestion looks good. I think there's still room for logging improvement but that's for another issue.
