### ISSUE TITLE
trusted zone is publicly accessible

### ISSUE THREAD

**Issue by pavels** [firewalld/firewalld#177]
When interface is placed in trusted zone, 2 rules are created in forward chain

-A FWDI_trusted -j ACCEPT
and
-A FWDO_trusted -j ACCEPT

the first rule is understandable, "everything from trusted zone is free to be forwarded anywhere" - i trust the computers in "trusted", so they can do whatever they want.

The second rule is very strange - "anybody can talk to trusted zone from outside"

If i have 2 interfaces, one is in "public" zone (which is very untrusted, anything can be there) and one in "trusted" zone, this second rule will allow any connections from the public zone be forwarded into trusted zone. That seem kind of strange.

Also if i want to implement the same behavior as "trusted" but without that rule, which allows anybody to talk to to trusted zone computers, it is impossible, because all FORWARD rules is hard coded in firewalld and cant be influenced from configuration (except port forwarding).

**Comment by TriMoon** [comment]
@pavels ,
> The second rule is very strange - "anybody can talk to trusted zone from outside"

What i see are: 
```
Chain FORWARD (policy ACCEPT)
target     prot opt source 
FORWARD_direct  all  --  0.0.0.0/0            0.0.0.0/0           
FORWARD_IN_ZONES_SOURCE  all  --  0.0.0.0/0            0.0.0.0/0           
FORWARD_OUT_ZONES_SOURCE  all  --  0.0.0.0/0            0.0.0.0/0           

Chain FORWARD_IN_ZONES_SOURCE (1 references)
target     prot opt source               destination         
FWDI_trusted  all  --  0.0.0.0/0            0.0.0.0/0            match-set <setname> src

Chain FORWARD_OUT_ZONES_SOURCE (1 references)
target     prot opt source               destination         
FWDO_trusted  all  --  0.0.0.0/0            0.0.0.0/0            match-set <setname> dst
```

Those rules add correct restrictions regarding forwarding because it:
  1) restricts **FWDI_trusted** with **src** matching entries in \<setname>,
  1)  and restricts **FWDO_trusted** with **dst**  matching entries in \<setname>.

The error in thought you make is that the FORWARD chain applies before the INPUT chain.
The reality is though: the FORWARD chain applies to packets **after** the INPUT chain has decided they are allowed.
Because the kernel can not forward packets that has not been accepted into the firewall chains yet.
eg. chain logic= INPUT->FORWARD->OUTPUT
See: https://en.wikipedia.org/wiki/Iptables#/media/File:Netfilter-packet-flow.svg

It means everything can be forwarded to the trusted zone.
That does NOT mean anything WILL be forwarded, because before something gets forwarded it will be processed by the input chains...

**Comment by pavels** [comment]
Well that means RedHat docs are wrong

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html-single/Security_Guide/index.html#sect-Security_Guide-Firewalls-Using_IPTables

as they say INPUT is used when the packet destination is current machine and not used when the packet is destined somewhere else and is just forwarded.

official documentation says the same http://www.netfilter.org/documentation/HOWTO//packet-filtering-HOWTO-6.html

Also my observations on CentOS 7 confirms, that you can actually forward packets from Public to Trusted without any additional rules.

"match-set <setname> src" - this is strange, on centos 7 this is not set. Can this have any influence?

**Comment by TriMoon** [comment]
Perhaps my explanation was wrong then...

Anyway ``match-set <setname> src`` will only be used when you use an ipset as source.

**Comment by erig0** [comment]
@pavels, firewalld zones are applied at ingress. But after ingress packets may be forwarded by the host freely between zones. I realize this may be different than zones in other firewalls, but firewalld has functioned this way since day one. Changing the behavior would require a lot of thought.

I'm marking this issue as an enhancement.

**Comment by steffann** [comment]
What is the currently acceptable solution for allowing traffic from trusted -> public, but not from public -> trusted? At least until the further thoughts are implemented :)

**Comment by pavels** [comment]
@erig0 well is is actually not working that way

trusted -> public - trusted is ingress i can forward everywhere, understandable
public -> trusted - public doesn't allow any communication (example) but packets will still be allowed to pass to trusted - so the pass/deny is actually decided by egress zone not by ingress

**Comment by steffann** [comment]
For now I have fixed it by adding a direct rule in `/etc/firewalld/direct.xml`:

    <?xml version="1.0" encoding="utf-8"?>
    <direct>
      <rule ipv="ipv6" table="filter" chain="FWDI_public_deny" priority="1000">
        -j REJECT --reject-with icmp6-adm-prohibited
      </rule>
    </direct>

**Comment by erig0** [comment]
@pavels, right. Right now the majority of filtering is on INPUT. firewalld lacks support for FORWARD chain filtering, see issue #2.

**Comment by sshambar** [comment]
I actually logged this issue against Fedora back in 2014, but progress on it stalled.
(https://bugzilla.redhat.com/show_bug.cgi?id=1097960)

I think it's clear that forwarding from "public" to "trusted" should be disabled by default... not every machine in the trusted zone will have a firewall... (if you have a NAT connection it's not really an issue for ipv4) but without a direct rule to block forwarding, all ipv6 hosts in the trusted zone are open to full port scans from the public zone (bad).

DDWRT, OpenWRT etc (and most off the shelf routers) all block ipv4/ipv6 WAN to LAN forwarding by default... seems like a reasonable and secure default.

**Comment by pavels** [comment]
@sshambar 

First - i implemented workaround some time ago - i do not use `trusted` anywhere, i use `internal` instead an have direct rule to allow forwarding from internal and vpn network cards  (i have interface names hardcoded)

Second - when filling this bug, my assumption was that `FWDI_trusted  all  --  0.0.0.0/0            0.0.0.0/0            ` is plain bug as i thought nobody sane would ever consider this as wanted behavior as this affects security of internal networks seriously (especially on IPV6, but even IPV4 - NAT should not be considered as security measure for various reasons) - i was wrong. I still think this is dangerous behavior as it is IMHO unexpected.  After reading various discussions concerning this and similar topics i think one of the problems is, that firewalld was designed as "desktop firewall" - something targeted on desktops with possibility to use GUI to configure it. Than it landed in RHEL / CentOS and here we are now.  I think if this is not addressed in any way (which seems like most likely outcome) - there should be at least clear warning in the docs, that it is designed and works like this and that use of firewalld on machines with routing / gateway duties should be done with care.

Or maybe just rename `trusted` to `DMZ` because that's what it actually is (depending on the definition of `DMZ` - under some definition it is still not secure enough to be considered `DMZ`).

**Comment by sshambar** [comment]
Well, investigating the current state of affairs (0.6.5 in Fedora 30), it appears that the bug you originally logged may be fixed (for internal zone anyway)...  internal uses the "default" target policy, the only generated rule in FWDI_internal is an icmp ACCEPT, and no FWDO_internal rules at all...

The trusted zone has a target=ACCEPT policy, and therefore adds ACCEPT rules to both FWDI_trusted and FWDO_trusted (which I still think is odd!) -- so it still permits forwarding _from_ all untrusted zones...

I think the current bug is that any "untrusted" zones (eg public, external) don't have a zone target of "%%REJECT%%"... if they did, they'd have a FWDI_public REJECT catch all rule that would apply before the trusted FWDO_trusted ACCEPT rule had a chance to permit the unwanted (public->trusted) forwarding...

Currently, I have a choice of 2 work arounds:

1) Modify trusted zone to use the target=default (rather than it's current ACCEPT, which really should be on the dmz zone, but isn't!).  This would prevent forwarding from any zone that doesn't have the target=ACCEPT policy (as it wouldn't just accept any/all unblocked forwarded packets)

2) Modify my untrusted zone (currently external) to use target=%%REJECT%%, so that forwarding to anywhere is denied.  I'll probably do that as it would still allow all my trusted zones to forward between themselves freely...
