### ISSUE TITLE
Add User Defined Ordering to Govern Resolution when Zone Sources Overlap

### ISSUE THREAD

**Issue by wmszeliga** [firewalld/firewalld#192]
When IP source ranges for zones overlap, the behavior (appears?) to be undefined. This may lead to confusion on the user-end. Consider the following settings where the public zone is the default zone:

    >firewall-cmd --zone=public --add-interface=en0
    success
    >firewall-cmd --zone=work --add-source=xxx.xxx.192.0/18
    success
    >firewall-cmd --zone=internal --add-source=xxx.xxx.251.128/25
    success
    >firewall-cmd --zone=internal --add-service=ssh
    success

The intent of this rule set is to allow ssh from machines on a subnetwork inside of a larger network. I understand that there are different ways to accomplish this (a rich rule in the 'work' zone, for example), however, the example above seems like an intuitive approach as well. 

If the above settings are used, and an ssh connection arrives from a machine in the subnetwork xxx.xxx.251.128/25, sometimes it is allowed through and sometimes it is not. What determines whether the connection is allowed through seems to be determined at the time firewalld is (re)loaded and the behavior then remains that way until firewalld is reloaded again. 

This behavior has burned my group at least once when we set up an entire batch of new machines which appeared to be functioning as desired until a building-wide power failure necessitated a reboot of all machines. When the machines came back up, none of the machines behaved as expected. 

I propose allowing the user to define the order of zone resolution to improve repeatability and help follow the principle of least surprise. When no ordering is defined by the user, a simple, default zone resolution could be imposed (and documented); perhaps something as simple as alphabetical order, or equally intuitive, increasing level of trust.

**Comment by bennetts2** [comment]
I think the zones are evaluated in lexical order, but it would be nice to have confirmation of that in the documentation. I've named my zones like I used to name my init scripts (e.g. "10_drop", "20_special", "30_internal", "40_external", "default"). If there's a better way to do it I'd love to see a documented example.

**Comment by aculver** [comment]
The zones with sources get turned into chains which are reached from the INPUT_ZONES_SOURCE chain. When it matches the first zone in the list, it uses a **goto** to reach the chain for the first zone. Because it used a **goto** and not a **jump** if there was no matching rule in the first chain, it returns all the way back to the INPUT chain. If the rules in the INPUT_ZONES_SOURCE were to use a **jump** instead, then it would continue evaluating with the rule for the next zone. 

In your example, if a host matched the sources of both your work and internal rules, it would evaluate the first for a match. If no match is found, it would evaluate the second. Currently, it only evaluates the first, then gives up if no rule matched.

Is there a reason firewalld can't use **jump** instead of **goto** here?

**Comment by erig0** [comment]
> Is there a reason firewalld can't use jump instead of goto here?

I believe that is by design. Traffic from a given source goes to one and only one zone. Allowing a fall-through to other zones can be very error prone and therefore a security issue.

**Comment by erig0** [comment]
In my opinion, firewalld should follow the same rules as routing. That is, the more specific prefix should have higher precedence. In @bennetts2's case, that means xxx.xxx.251.128/25 should always be used for traffic from the xxx.xxx.251.128/25 network.

**Comment by bennetts2** [comment]
Yes, I agree, but how does firewalld decide which of two "ipset" zones should have higher precedence?
I don't specifically disagree with the current implementation, but I would like there to be some documentation that makes it clear what order will be used for rules.

**Comment by aculver** [comment]
> That is, the more specific prefix should have higher precedence.

Zones can have multiple sources. Two zones could each have 2 sources, one of each being more specific than the other's. If you insist that a source can only be in one zone, then you need a different way to define precedence.

I also disagree that firewalld should follow the same rules as routing. This is about policy, not routing. Similar to how an IP can exist in multiple tagged vlans, and different policy can be applied to each vlan. A source should be able to exist in multiple zones. I should be able to apply policy to my network without having to redefine that policy at each and every zone that includes a narrower source.

**Comment by erig0** [comment]
> how does firewalld decide which of two "ipset" zones should have higher precedence?

I think it's undefined in firewalld and would depend on how they're added to iptables. ipset natively supports a "nomatch" option when adding. Which means you could remove a /24 from your block of /16. That way your zones would not have overlapping addresses. I don't think firewalld supports this option. Feel free to open an enhancement request.

**Comment by erig0** [comment]
@aculver, would a zone priority work? That would guarantee zoneA is considered before zoneB. It would be similar to how we have a priority for --direct rules.

**Comment by aculver** [comment]
@erig0, I think a priority is needed. Currently this can only be kludged by manipulating the order by numbering your zone names as @bennetts2 showed. 

What I want (which is off-topic but related to this issue) is to allow a source/IP to apply to multiple zones by using jump instead of goto, or at least give the administrator the option of doing this. Should I create an enhancement request for this?

**Comment by erig0** [comment]
@aculver 

> I think a priority is needed.

Please open an enhancement request.

> is to allow a source/IP to apply to multiple zones by using jump instead of goto

I disagree with this approach. As I said on the mailing list; zones are meant to isolate traffic. If this type of functionality is required, I'd rather see something more explicit like allowing the user to specify a zone to --set-target. This would be goto at the end of the zone's chain - just like --set-target=ACCEPT is today. But honestly I think rich rules with service=foo and ipsets is sufficient.

**Comment by aculver** [comment]
@erig0 

> Please open an enhancement request.

Is that not what this issue is? Do I need to create enhancement requests somewhere else?

> I think rich rules with service=foo and ipsets is sufficient.

It may be sufficient to make iptables do what you need it to do, but this seems like a less clean way of doing it. I could just create my entire ruleset using a series of rich rules, but this negates the power of zones. I might as well just use iptables directly at that point. 

I was trying to embrace the zones of firewalld, but to me, stopping evaluation after the first zone match seems unintuitive and makes changes more difficult, as you now have to apply service changes to multiple zones. I don't see zones as isolating traffic, but as applying policy, which will often needs to be applied to overlapping sources.

Something like a --continue option on a zone to tell firewalld to continue evaluating the next zone if the current zone doesn't match would suffice. The effect of using --continue would be as simple as making the iptables chain use jump instead of goto.

**Comment by erig0** [comment]
> Is that not what this issue is? Do I need to create enhancement requests somewhere else?

My mistake. We can use this issue for the priority enhancement.

> I could just create my entire ruleset using a series of rich rules, but this negates the power of zones.

You can use the zones services for the common services. You only need rich rules for the "narrow" cases.

> stopping evaluation after the first zone match seems unintuitive and makes changes more difficult

I disagree. I think allowing traffic to ingress multiple zones is unintuitive. I'm not aware of any firewall implementations that allow that. Do you know of any?

> Something like a --continue option on a zone to tell firewalld to continue evaluating the next zone

This could be done, but is dependent on implementing zone priorities to guarantee the ordering.
