### ISSUE TITLE
Pagure

### ISSUE THREAD

**Issue by BenjaminLefoul** [firewalld/firewalld#200]
Hi Thomas,

Any plan to migrate from github to pagure?

Lef

**Comment by t-woerner** [comment]
Hi Lef,

at the moment I do not have plans to migrate to pagure.

Since I have been migrating from fedorahosted to github there is a lot more interest in the firewalld project. On fedorahosted there have been nearly no contributions and request from other people especially for other distributions.

The interaction with contributors for requests and also the handling of pull requests is important, this has been one of the big issues with fedorahosted. Additionally I needed a place for a new firewalld.org home page - the wiki on fedorahosted was simply not enough and was lacking an integration with the source repo.

Regards,
Thomas
