### ISSUE TITLE
Multicast UDP packets (MDNS/Bonjour protocol) blocked by default?

### ISSUE THREAD

**Issue by badgernaut** [firewalld/firewalld#21]
Hi,

Fedora 22 x86_64 (latest Beta): firewalld (v0.3.13-7.fc22) seems to be blocking the aforementioned packets, preventing the auto-discovery of local contacts in Empathy (default Fedora IM client), and also Gnome's "People Nearby" functionality (through control-centre->Online Accounts).

Is this expected? are there some settings/config I can play with to get this to work?

Thanks,

**Comment by a4lg** [comment]
I think this is expected since it only allows SSH and DHCPv6 client by default (default configuration / default zone). You can do either:

* Add MDNS service to allow list
* Configure zones (other than default one)

Fortunately, firewalld has `mdns` service definition by default.

If you need to add MDNS service to "allow" list (in the default zone `public`), run following commands as root. I think this method works well for you (there is a GUI for firewalld but I haven't used yet).
``firewall-cmd --permanent --add-service=mdns; firewall-cmd --reload``
Note that this allows MDNS on all connected networks (unless you configure zones) and you may need to configure zones to separate specific networks.

For more information (to configure firewalld), see firewalld documentation (e.g. manpage) and a Wiki page on the Fedora Project (https://fedoraproject.org/wiki/FirewallD).

**Comment by badgernaut** [comment]
Thanks; that makes sense.

I think this is an issue for the Gnome/Fedora people, to ensure they properly configure firewalld for the services they want to enable out of the box.

I'll take it to them.

Cheers,

badgernaut

**Comment by t-woerner** [comment]
@badgernaut
mdns is enabled by default in the public and work zones in Fedora. Additionally there is a very open firewall configuration in the Workstation product since Fedora-21.

Since Fedora-22 there are no product specific firewalld-config- sub packages anymore, but the product specific config file is linked to /etc/firewalld/firewalld.conf.

Which product are you using and which config file is linked to /etc/firewalld/firewalld.conf?

@a4lg
Instead of reloading, you could easily enable mdns in runtime and permanent:
``firewall-cmd --add-service=mdns; firewall-cmd --permanent --add-service=mdns``
One call without ``--permanent`` in the runtime environment and one with.

**Comment by badgernaut** [comment]
@t-woerner 
I see 'mdns' service is indeed specified in the FedoraWorkstation.xml zone (/etc/firewalld/firewalld.con is linked to firewalld-workstation.conf, as expected).

I am trying to use Empathy which utilises the telepathy-salut stack underneath (for the Bonjour protocol).

Please see RH bug report for more detail: https://bugzilla.redhat.com/show_bug.cgi?id=1222469

Even though I can see this is defined in the zone, it still seems to block mDNS/Bonjour packets...

**Comment by erig0** [comment]
@badgernaut, Is this still an issue? The report is very old and the bugzilla issue is closed.

**Comment by jpeter01** [comment]
In openSUSE 15.0 this is still an issue. I have the following configuration:
`firewall-cmd --list-all
home (active)
  target: default
  icmp-block-inversion: no
  interfaces: br0 eth0 tap0
  sources: 
  services: ssh mdns samba-client dhcpv6-client apache2 apache2-ssl http https kdeconnect-kde minidlna nfs nfs3 openvpn pulseaudio samba sane upnp-client vnc-server tigervnc ipp ipp-client tigervnc-https apcupsd mountd rpc-bind
  ports: 6566/tcp 6566/udp 8200/tcp 1900/udp 10000-10100/tcp 10000-10100/udp 631/tcp 631/udp 8080/tcp 1194/tcp 30000-65535/udp 30000-65535/tcp 10000-60000/tcp 10000-60000/udp
  protocols: 
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules:`

The corresponding iptables rules are in the attachment. 

The miniDLNA upnp doesn't shows up when using a VPN connection, until the firewalld is running. Sometimes it disappears from the LAN too. If firewalld is not running, the upnp show up when I'm using the VPN.

**Comment by erig0** [comment]
If symptoms occur while the VPN is active then it may be a routing issue. Can you verify that mdns packets are actually sent out to the LAN and not through the VPN?

Does mdns work while the VPN is _NOT_ active?

**Comment by erig0** [comment]
Closing this super old bug with no feedback. If you provide feedback then it can be reopened.
