### ISSUE TITLE
Service Required : Apache2

### ISSUE THREAD

**Issue by jshand2015** [firewalld/firewalld#286]
Hi there.  i've noticed that when i've tried to get a http server working, the service doesn't exist, except for the close cousins http and https.

**Comment by Rudi3** [comment]
@jshand2015 what do you mean by that? You have to enable http in the appropriate zone in order to allow traffic to your server (e.g. apache) ([See the docs](http://www.firewalld.org/documentation/howto/open-a-port-or-service.html)). [This also should be a good Guide for getting Started](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-using-firewalld-on-centos-7).

An example would be:
`firewall-cmd --zone=public --add-service=http`
Adding the service permanently (kept after reboot or reload):
`firewall-cmd --permanent --zone=public --add-service=http`

**Comment by jshand2015** [comment]
thanks for that.  i realised it was something to do with the opensuse yast2 module.  i have now sent the issue their way.  you can now delete this as it is now invalid

**Comment by Rudi3** [comment]
@jshand2015 glad I could help you. I dont have any rights on this repo; I would recommend to close the issue (as the author you can do that) and keep it around in case someone has the same problem in the future.
