### ISSUE TITLE
ipset not removed by firewalld

### ISSUE THREAD

**Issue by jfroche** [firewalld/firewalld#330]
Hello,

It looks like firewalld doesn't succeed to remove one ipset.

```
# ipset list bird
Name: bird
Type: hash:ip
Revision: 1
Header: family inet hashsize 1024 maxelem 400
Size in memory: 16528
References: 0
Members:
# firewall-cmd --info-ipset=bird
bird
  type: hash:ip
  options: maxelem=400 family=inet
  entries: 
# firewall-cmd --delete-ipset=bird --permanent
success
# ipset list bird
Name: bird
Type: hash:ip
Revision: 1
Header: family inet hashsize 1024 maxelem 400
Size in memory: 16528
References: 0
Members:
# firewall-cmd --info-ipset=bird
bird
  type: hash:ip
  options: maxelem=400 family=inet
  entries: 
# ls -l /etc/firewalld/ipsets/bird.xml
ls: cannot access /etc/firewalld/ipsets/bird.xml: No such file or directory
# tail -n 7 /var/log/firewalld
2018-04-20 17:04:50 DEBUG1: direct.passthrough('ipv4', '-D','FORWARD','-j','DOCKER-ISOLATION')
2018-04-20 17:04:50 DEBUG1: direct.passthrough('ipv4', '-I','FORWARD','-j','DOCKER-ISOLATION')
2018-04-20 17:07:29 DEBUG1: getIPSetSettings(bird)
2018-04-20 17:08:16 DEBUG1: config.getIPSetByName('bird')
2018-04-20 17:08:16 DEBUG1: config.ipset.0.remove()
2018-04-20 17:08:16 DEBUG1: config.ipset.0.Removed('bird')
2018-04-20 17:08:26 DEBUG1: getIPSetSettings(bird)
```

from what I read here: https://github.com/firewalld/firewalld/blob/v0.4.4.4/src/firewall/core/fw_ipset.py#L79
I should have received a message if removal failed.
Do I forget something ?

environment:
 - CentOS Linux release 7.4.1708 (Core)
 - firewalld 0.4.4.4-6

**Comment by erig0** [comment]
firewalld only allows creating/deleting ipsets with the `--permanent` flag. As with all other commands the `--permanent --delete-ipset` command will not remove the ipset from the runtime. This is expected behavior.

The problem here is firewalld

* doesn't have an option to remove the runtime ipset  
This is probably because it's difficult to detect what all has dependencies on the ipset. The direct interface is especially problematic, but rich rules are also problematic. Forcing a reload of firewalld avoids these issues.
* doesn't clean up or flush existing ipsets on a restart  
Flushing would be inline with what happens to iptables/ebtables. But it would be a behavior change and would likely have to be added with a configuration knob.

I'm not sure how best to solve this and will have to think about it more.

**Comment by zack7wong** [comment]
You need to use `firewall-cmd --reload` or `systemctl restart firewalld`

**Comment by mpolitaev** [comment]
@zack7wong created duplicate because didn't see this #573 and FYI
`firewall-cmd --reload` or `systemctl restart firewalld` didn't help in my case, i still see "deleted" ipset in output `ipset -L`

**Comment by erig0** [comment]
> @zack7wong created duplicate #573 because didn't see this and FYI
> `firewall-cmd --reload` or `systemctl restart firewalld` didn't help in my case, i still see "deleted" ipset in output `ipset -L`

Correct. This is noted above in https://github.com/firewalld/firewalld/issues/330#issuecomment-385780482.
