### ISSUE TITLE
file xxx.at included several times

### ISSUE THREAD

**Issue by mbiebl** [firewalld/firewalld#363]
While running the test-suite, I get multiple warnings on stderror:
```
testsuite.at:8: warning: file `firewall-cmd.at' included several times
testsuite.at:8: warning: file `regression.at' included several times
regression.at:2: warning: file `regression/rhbz1514043.at' included several times
regression.at:3: warning: file `regression/rhbz1498923.at' included several times
regression.at:4: warning: file `regression/pr181.at' included several times
regression.at:5: warning: file `regression/gh287.at' included several times
regression.at:6: warning: file `regression/individual_calls.at' included several times
regression.at:7: warning: file `regression/rhbz1534571.at' included several times
regression.at:8: warning: file `regression/gh290.at' included several times
regression.at:9: warning: file `regression/icmp_block_in_forward_chain.at' included several times
regression.at:10: warning: file `regression/pr323.at' included several times
regression.at:11: warning: file `regression/rhbz1506742.at' included several times
testsuite.at:8: warning: file `python.at' included several times
```

Afaics, this is caused by https://github.com/firewalld/firewalld/blob/master/src/tests/testsuite.at#L8 which includes the .at files twice, once for nftables and once for iptables. 
Not sure why that is necessary

**Comment by erig0** [comment]
It's intentional because firewalld runs a subset of the testsuite twice - once for each firewall backend (nftables and iptables). This is done to avoid duplicating the same tests and to also make sure new tests are added for all backends. I don't think autotest provides a way to mask the warning.

One way to avoid these is to add another set of makefiles in subdirectories; `src/tests/nftables`, `src/tests/iptables`, `src/tests/offline`. Then they can each include the .at files without throwing a warning. But that also means you have multiple tests with the same number. All of them would have a test numbered "1". So running the following to reproduce a failure

    # make check TESTSUITEFLAGS="1 -v -d"

will actually run 3 different tests. I'm not sure that is worth avoiding a harmless warning. To run a individual test you need to do

    # make -C src/tests/iptables check-local TESTSUITEFLAGS="1 -v -d"

Do you have any better ideas?

**Comment by erig0** [comment]
I found another solution. m4sugar is the one throwing the warning. We can avoid it by calling the m4 builtin directly.
e.g.

    m4_define([my_include], [m4_builtin([include], [$1])])

I'll probably give this a go.
