### ISSUE TITLE
CleanupOnExit=yes removes bridge interfaces

### ISSUE THREAD

**Issue by seblu** [firewalld/firewalld#533]
Hello,

When `CleanupOnExit=yes` in `firewalld.conf`, firewalld destroy bridges interfaces when it removes the bridge module. Cleanup should remove only configuration added (dirtied?) by firewalld.

I found this searching why my `docker0` interface was missing when I restart firewalld.

#### Steps to reproduce
```
$ brctl addbr foo
$ brctl show
bridge name	bridge id		STP enabled	interfaces
foo		8000.a64bd07199ed	no		
$ firewalld --debug 2 --nofork
...
DEBUG2: <class 'firewall.core.modules.modules'>: /usr/bin/rmmod bridge
...
$ brctl show
```
The output  was made on Arch Linux with firewalld 0.7.2.

**Comment by erig0** [comment]
A full restart or `--complete-reload` of firewalld will attempt to unload kernel module nf_conntrack and anything directly/indirectly depending upon that kernel module, which in your case includes the bridge module. Since many modules are implicitly loaded by iptables/nftables rules there is no way for firewalld to track what kernel modules its ruleset caused to be loaded.

You can use `--reload` which does not attempt to unload modules.

It's been on my TODO list to completely remove the kernel module unloading as it's pretty unnecessary now-a-days.

Also see https://bugzilla.redhat.com/show_bug.cgi?id=1520532.
