### ISSUE TITLE
Conflict with CNI DNAT rule and top-level accept of DNAT'd packets

### ISSUE THREAD

**Issue by st1971** [firewalld/firewalld#556]
I have recently upgraded from Fedora 30 to 31 and the default firewall rules seem to have changed between the 2 versions.

In F30, which used firewalld 0.6.5 the INPUT and FORWARD chains would start with something along the lines of:
```
ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
```
In F31, which uses firewalld 0.7.2 the INPUT and FORWARD chains start with something along the lines of:
```
ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED,DNAT
```

The DNAT option means that I am struggling to put any control on what subnets can access a container on a host as this kind of make's it world accessible.  Is there any way of changing this behavior as I would like some additional control over container access..

There is a similar rule in the filter_FORWARD chain when using nftables as the backend.

**Comment by erig0** [comment]
Can you describe more about how accepting packets with DNAT state is affecting you? With containers they are likely using SNAT/masquerade.

**Comment by st1971** [comment]
Thank you for taking the time to get back to me on this, it's appreciated.

One of the rules that is setup in the nat table by CNI networking is a port forward to the container address:

`    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:5000 to:10.88.0.11:5000`

This rule is processed before the filter table so when it hit's the first rule in the forward chain the packet is accepted without any other filter rules being applied.  If I delete and recreate the first rule in both the input and forward chains manually using iptables directly dropping the DNAT option then all of my filters are processed and i can block traffic to the container for some sub nets. 

I have attached a copy of the rule in the nat table outputted using iptables -t nat -n -L -v a copy of the output of iptables -n -L -v and trace output so the order that rules are firing can be seen.

[nat-container.txt](https://github.com/firewalld/firewalld/files/4032362/nat-container.txt)
[general.txt](https://github.com/firewalld/firewalld/files/4032365/general.txt)
[trace.txt](https://github.com/firewalld/firewalld/files/4032366/trace.txt)

**Comment by erig0** [comment]
This changed in commit 7235f76a818329e3aaba2f8c1444f15b4af586c2 (6190a2b99e4f92881873633cc8a500d466e4ead9 for nftables). The short explanation is firewalld's "forward port" implementation _was_ using packet marks and now instead relies on match the DNAT conntrack state. This was changed because it

- simplified the rules
- removed any conflicts with anything else using packet marks
- allowed us to remove mark allocation and tracking

Why doesn't CNI scope the DNAT rule to an saddr or daddr range?

**Comment by st1971** [comment]
It would have to be a saddr i would guess, but this would mean that podman etc would have to pass an appropriate saddr to CNI for the rules to be setup new rule is setup for each container that's spun up, the assumption from the CNI project is that you will block / allow traffic to the port that is being forwarded to the container.
If the forward or input direct rules could be put at a higher priority than the DNAT then direct rules could be used to explicitly reject / drop traffic.

**Comment by erig0** [comment]
> If the forward or input direct rules could be put at a higher priority than the DNAT then direct rules could be used to explicitly reject / drop traffic.

With the nftables backend direct rules occur before any of the other rules. This includes the top-level accept of exisiting/DNAT'd connections.

**Comment by st1971** [comment]
Had another look at this last night, switched to nftables backend was then able to put a blocking rule into the filter table to block unwanted access, which make this work for me right now.  But it does feel the wrong way round.

Thanks again for your help on this.

**Comment by erig0** [comment]
With the iptables backend you could use `--direct --add-passthrough` which will allow you to inject rules before the top-level accept of existing/dnat connections.
e.g.

    firewall-cmd --permanent --dircect --add-passthrough ipv4 -I FORWARD 1 -s 10.10.10.0/24 -j DROP

**Comment by st1971** [comment]
Thank you will give that a try as well, been using iptables as the back end as it's the default on F30/F31...  Sorry to ask a question that is off this topic but why are direct rules implemented using iptable rather than nft when nftables is the backend?

**Comment by erig0** [comment]
> Thank you will give that a try as well, been using iptables as the back end as it's the default on F30/F31... Sorry to ask a question that is off this topic but why are direct rules implemented using iptable rather than nft when nftables is the backend?

There are tools to translate iptables --> nftables, but they're not 100% complete and never will be. As such we took the stance to not automatically translate them in firewalld. For many use cases using iptables in concert with nftables is fine.

There is currently no nftables equivalent of direct rules, because there hasn't been much driving force. IMO, its a better idea to enhance rich rules. As for forward/output filtering, that's also in development.

**Comment by dossy** [comment]
This is particularly problematic because you cannot define `DROP` rules in the `nat` table (i.e., in your `PREROUTING` chain), so if you want to "ban" a source IP with a `DROP` rule in your `filter` table's `INPUT` and `FORWARD` chains, it gets added **after** the `ctstate RELATED,ESTABLISHED,DNAT` rule, which prevents the `DROP` rule from being applied to any DNAT'ed traffic.

Using `--direct --add-passthrough` is a work-around, but not pushing NAT'ed traffic through the `INPUT` and `FORWARD` chains properly is a bug, IMHO.

**Comment by erig0** [comment]
> This is particularly problematic because you cannot define `DROP` rules in the `nat` table (i.e., in your `PREROUTING` chain)

Not sure what your drop rule looks like, but you can drop in raw PREROUTING. However raw occurs _before_ nat.

> Using `--direct --add-passthrough` is a work-around, but not pushing NAT'ed traffic through the `INPUT` and `FORWARD` chains properly is a bug, IMHO.

The NAT is occurring out of band of firewalld. I'm not sure how you expect firewall to cooperate with something it doesn't even know about.

There are two workarounds:
  1. CNI only DNATs wanted traffic (e.g. scope to saddr)
     - right now it's DNATing everything and then the user relies on firewalld to drop a subset of the traffic
  2. Use a direct passthrough rule.
