### ISSUE TITLE
Lack of ability to handle REDIRECT and TPROXY with nftables backend

### ISSUE THREAD

**Issue by proletarius101** [firewalld/firewalld#640]
```shell
sudo firewall-cmd --direct --add-rule ipv4 nat PREROUTING 0 -p tcp redirect --to-port 8080
```

will result in

```
table ip nat {
    chain PREROUTING {
        meta l4proto tcp counter packets 0 bytes 0 # xt_REDIRECT
    }
}
```

I'm not quite sure what \```# xt_REDIRECT` `` means. TMK it's a kernel module used in iptables. It's not supposed to appear in nftables. I only have knowledge of this kind of usage:

```
sudo nft add rule ip nat PREROUTING ip protocol tcp counter redirect to :8080
```

Similarly, executing

```shell
sudo firewall-cmd --direct --add-rule ipv4 mangle PREROUTING 0 -p udp -j TPROXY --on-port 8080 --tproxy-mark 1
```

will result in 

```
table ip mangle {
    chain PREROUTING {
		meta l4proto udp counter packets 0 bytes 0 # xt_TPROXY
    }
}
```

In both cases, the `#xt_xxx` usage doesn't take any effect on redirection or transparent proxy.

**Comment by erig0** [comment]
It looks like you're using a distribution in which `iptables` is the `nf_tables` variant instead of the `legacy` variant.
```
# iptables -V
iptables v1.8.4 (nf_tables)
```

This means `iptables` is using the `nftables` kernel infrastructure, but the matching code is using the same code as `legacy` `iptables`. As a consequence the iptables rules will show up in `nft list` output as well as `iptables -L`. When `nftables` is compiled with `--with-xtables` support `nft list` will try to convert the `iptabels` rules into `nftables` equivalents. If it cannot, then it shows the original (as best it can) `iptables` rule as a comment.

You're rules are still in iptables. Just use `iptables -L` to show them as you would normally.
