### ISSUE TITLE
Select zone by wifi SSID or equivalent

### ISSUE THREAD

**Issue by LecrisUT** [firewalld/firewalld#839]
I'm sorry if this is already implemented, but I couldn't find any guides or documentation about this.

**What would you like to be added**:
I would want to be able to switch between firewall zones `trusted`, `internal`, `public`, etc. depending on which wifi SSID the device is currently connected to. I realize that there could be an issue if someone creates a wifi with the same SSID name, so maybe there's a better approach to uniquely identify that network.

**Why is this needed**:
This could be useful for example when exposing `kdeconnect` only to trusted networks. This could also be useful if a portable laptop is also used as part of a mesh to backup some configurations and you want those services not be exposed to different networks that use the same IP netmask.

**Comment by erig0** [comment]
If you use NetworkManager then this already works by setting the zone in the NetworkManager connection settings. IMO, understanding WiFi connections/APs is outside the scope of firewalld. Given that this can be done via NetworkManager and probably network-scripts I'm NAKing this feature. Futhermore, you can use source addresses (if you know them) and avoid the interfaces entirely.

Your options:
1. Use NetworkManager
2. Use `--add-source` instead of `--add-interface`
