### ISSUE TITLE
firewall-cmd runtime ot permanent fails with "Warning: NOT_ENABLED: wlp2s0"

### ISSUE THREAD

**Issue by jjgalvez** [firewalld/firewalld#976]
**What happened**: tried to add a port rule to with the command 
```
firewall-cmd --zone=home --add-port=8000/tcp
firewall-cmd --runtime-to-permanent
```
this reports 
```
Warning: NOT_ENABLED: wlp2s0
success
```
however restarting the firewalld shoes the port is not enabled.

**What you expected to happen**:
The port to be made permanent

**How to reproduce it (as minimally and precisely as possible)**:
see above

**Anything else we need to know?**:
downgrading to version 1.0.3 resolves the issue

**Environment**:
- Firewalld Version: 1.1.1
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): 
# FirewallBackend
FirewallBackend=nftables
- OS (e.g: `cat /etc/os-release`): Arch Linux
- Others:

**Comment by ciencia** [comment]
Same issue for me. openSUSE Tumbleweed
Firewalld Version: 1.1.1, but I can't get a previous version because the system has been installed 3 days ago.

The workaround for me was to add --permanent when adding the new rule

Example:

Trying to add a rule

```
> sudo firewall-cmd --info-zone=dmz
dmz (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp3s0
  sources: 
  services: ftp ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

> sudo firewall-cmd --zone=dmz --add-port=5023-5033/tcp
success
```

`--runtime-to-permanent` gives warning but success... on `--reload` change is lost

```
> sudo firewall-cmd --runtime-to-permanent
Warning: NOT_ENABLED: enp3s0
success

> sudo firewall-cmd --info-zone=dmz
dmz (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp3s0
  sources: 
  services: ftp ssh
  ports: 5023-5033/tcp
  protocols: 
  forward: yes
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

> sudo firewall-cmd --reload
success

> sudo firewall-cmd --info-zone=dmz
dmz (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp3s0
  sources: 
  services: ftp ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```

Next try with `--permanent`

```
> sudo firewall-cmd --permanent --zone=dmz --add-port=5023-5033/tcp
success

> sudo firewall-cmd --reload 
success

> sudo firewall-cmd --info-zone=dmz
dmz (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp3s0
  sources: 
  services: ftp ssh
  ports: 5023-5033/tcp
  protocols: 
  forward: yes
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```

**Comment by todoleza** [comment]
Confirmed as present on `firewalld-1.2.0-3.fc37.noarch` (rawhide)\
There's now also downstream bugzilla for the issue [rhbz#2112982](https://bugzilla.redhat.com/show_bug.cgi?id=2112982)

The issue is not occurring when NetworkManager kept stopped during firewalld start and the `--runtime-to-permanent` call. Starting NetworkManager even after firewalld restart causes the bug to reappear.

**Comment by erig0** [comment]
Hi all, this has been fixed in will be in the next firewalld stable release.

You can file an issue with your respective distributions and they may be able to backport this fix.

**Comment by jjgalvez** [comment]
Fantastic thank you!

**Comment by warrenc5** [comment]
confirm fixed in debian bookworm/sid firewall-config (1.2.1-1.1)
